laced/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from core import views as core_views
from users import views as user_views
from checkout import views as checkout_views
from products import views as product_views
from cart import views as cart_views
from marketing import views as marketing_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", core_views.home_view, name="home"),
    path("login/", user_views.login_view, name="login"),
    path("logout/", user_views.logout_view, name="logout"),
    path("signup/", user_views.signup_view, name="signup"),
    path("account/", user_views.account_view, name="account"),
    path(
        "account/addresses/",
        user_views.account_addresses_view,
        name="account_addresses",
    ),
    path("account/orders/", user_views.account_orders_view, name="account_orders"),
    path(
        "account/favourites/",
        user_views.account_favourites_view,
        name="account_favourites",
    ),
    path("products/", product_views.products_view, name="products"),
    path("products/add", product_views.add_product, name="add_product"),
    path(
        "products/edit/<int:product_id>",
        product_views.edit_product,
        name="edit_product",
    ),
    path(
        "products/delete/<int:product_id>",
        product_views.delete_product,
        name="delete_product",
    ),
    path(
        "products/<int:product_id>/",
        product_views.product_detail_view,
        name="product_detail",
    ),
    path("products/add_to_cart/", cart_views.add_to_cart, name="add_to_cart"),
    path("cart/", cart_views.cart_view, name="cart"),
    path(
        "cart/update_cart_quantity/<int:cart_item_id>/<int:quantity>/",
        cart_views.update_cart_quantity,
        name="update_cart_quantity",
    ),
    path(
        "cart/remove_from_cart/<int:cart_item_id>/",
        cart_views.remove_from_cart,
        name="delete_cart_item",
    ),
    path(
        "products/<int:product_id>/favourite/",
        user_views.add_remove_user_favourite,
        name="favourite",
    ),
    path("checkout/", checkout_views.checkout_view, name="checkout"),
    path(
        "checkout/confirmation/",
        checkout_views.checkout_confirmation_view,
        name="confirmation",
    ),
    path(
        "checkout/change_address/",
        checkout_views.checkout_change_address,
        name="checkout_change_address",
    ),
    path(
        "create_payment_intent/",
        checkout_views.create_payment_intent,
        name="create_payment_intent",
    ),
    path(
        "add_payment_intent_address/",
        checkout_views.add_payment_intent_address,
        name="add_payment_intent_address",
    ),
    path("stripe_webhook/", checkout_views.stripe_webhook, name="stripe_webhook"),
    path("subscribe/", marketing_views.subscribe, name="subscribe"),
    path("__debug__/", include("debug_toolbar.urls")),
]

# USED TO SERVE MEDIA FILES IN DEVELOPMENT
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models


class CartItem(models.Model):
    """
    Represents an item in a cart.

    Attributes:
        item (ProductVariant): The product variant associated with the cart item.
        cart (Cart): The cart that the item belongs to.
        quantity (int): The quantity of the item in the cart.
    """

    item = models.ForeignKey("products.ProductVariant", on_delete=models.CASCADE)
    cart = models.ForeignKey("cart.Cart", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.quantity}no. {self.item.product.name}"


class Cart(models.Model):
    """
    Represents a cart for a user.

    Attributes:
        user (users.User): The user associated with the cart.
        session (str): The session ID associated with the cart.
    """

    user = models.OneToOneField(
        "users.User", on_delete=models.CASCADE, default=None, null=True, blank=True
    )
    session = models.CharField(max_length=32, default=None, null=True, blank=True)

    def add_item(self, product, quantity):
        """
        Adds an item to the cart.

        Args:
            product: The product to be added.
            quantity (int): The quantity of the product to be added.

        Returns:
            CartItem: The created or updated cart item.
        """
        cart_item = CartItem.objects.filter(item=product, cart=self)
        if cart_item.exists():
            cart_item = cart_item.first()
            cart_item.quantity = cart_item.quantity + quantity
            cart_item.save()
            return
        return CartItem.objects.create(item=product, cart=self, quantity=quantity)

    def remove_item(self, product):
        """
        Removes an item from the cart.

        Args:
            product: The product to be removed.

        Returns:
            None
        """
        return CartItem.objects.get(item=product, cart=self).delete()

    def get_total_items(self):
        """
        Calculates the total quantity of items in the cart.

        Returns:
            int: The total quantity of items in the cart.
        """
        items = self.cartitem_set.all()
        total_quantity = 0
        for item in items:
            total_quantity += item.quantity
        return total_quantity

    def get_total_price(self):
        """
        Calculates the total price of all items in the cart.

        Returns:
            float: The total price of all items in the cart.
        """
        items = self.cartitem_set.all()
        total_price = 0
        for item in items:
            total_price += item.quantity * item.item.product.get_price()
        return total_price

    def as_dict(self):
        """
        Converts the cart to a dictionary representation.

        Returns:
            dict: A dictionary representation of the cart.
        """
        items = {"items": []}
        for item in self.cartitem_set.all():
            item = dict({"item": item.item.id, "quantity": item.quantity})
            items["items"].append(item)
        return items

products/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.utils.translation import gettext as _
import os


class Product(models.Model):
    """
    Product model for storing product information.
    Attributes:
        name (str): Product name
        sku (str): Product SKU (Stock Keeping Unit)
        - must be unique and exactly 6 numerical characters
        description (str): Product description
        category (str): Product category
        price (float): Product price, 2 decimal places

    """

    name = models.CharField(_("Product Name"), max_length=50)
    sku = models.CharField(
        _("SKU"),
        max_length=10,
        unique=True,
        help_text="SKU must be unique and exactly 6 numerical characters",
        validators=[
            RegexValidator(
                regex="[0-9]{6}", message="SKU must be exactly 6 numerical characters"
            )
        ],
    )
    description = models.TextField(_("Product Description"), max_length=500)
    category = models.ForeignKey(
        "products.ProductCategory",
        on_delete=models.SET_DEFAULT,
        default=None,
        null=True,
        blank=True,
    )
    price = models.DecimalField(decimal_places=2, max_digits=10)
    sale_price = models.DecimalField(
        decimal_places=2, max_digits=10, default=None, blank=True, null=True
    )
    is_featured = models.BooleanField(_("Featured Product?"), default=False)

    def __str__(self):
        return self.name

    def get_price(self):
        if self.sale_price:
            return self.sale_price
        return self.price


class ProductCategory(models.Model):
    """
    Product category model for storing product categories.
    """

    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


def upload_to_product_img(instance, filename):
    """
    Defines the upload path for product images.
    """

    filename = os.path.basename(filename)
    return os.path.join("product_imgs", filename)


class ProductImage(models.Model):
    """
    Product image model for storing product images.
    """

    image = models.ImageField(_("Image"), upload_to=upload_to_product_img)
    product = models.ForeignKey(
        "products.Product",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None,
    )


class ProductVariant(models.Model):
    """
    Product variant model for storing product variants.
    Defines the product size and quantity in stock.
    """

    SIZES = [
        ("5.5", "UK 5.5"),
        ("6", "UK 6"),
        ("6.5", "UK 6.5"),
        ("7", "UK 7"),
        ("7.5", "UK 7.5"),
        ("8", "UK 8"),
        ("8.5", "UK 8.5"),
        ("9", "UK 9"),
        ("9.5", "UK 9.5"),
        ("10", "UK 10"),
        ("10.5", "UK 10.5"),
        ("11", "UK 11"),
        ("12.5", "UK 12.5"),
        ("13", "UK 13"),
    ]
    product = models.ForeignKey(
        "products.Product", related_name="variants", on_delete=models.CASCADE
    )
    size = models.CharField(_("Size"), max_length=50, choices=SIZES)
    quantity = models.PositiveIntegerField(
        _("Qty in stock"), blank=True, default=0, null=True
    )

    def __str__(self):
        return f"{self.product.name}; {self.size}"

cart/views.py
from django.shortcuts import render
from products.models import ProductVariant
from django.http import HttpResponse
from .models import Cart, CartItem


def add_to_cart(request):
    """
    Add a product to the cart.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response containing the cart counter badge.
    """
    product = ProductVariant.objects.filter(
        id=request.POST.get("product_variant")
    ).first()
    if request.user.is_authenticated:
        cart = Cart.objects.get_or_create(user=request.user)[0]
    else:
        cart = Cart.objects.get_or_create(session=request.session.session_key)[0]
    quantity = int(request.POST.get("quantity"))
    cart.add_item(product, quantity)
    cart_total_quantity = cart.get_total_items()
    badge_quantity = cart_total_quantity
    if badge_quantity > 99:
        badge_quantity = "99+"
    return HttpResponse(
        (
            "<div id='cart-counter-badge' "
            "hx-swap-oob='true' "
            "class='w-5 h-5 text-center text-white "
            "flex items-center justify-center rounded-full "
            "bg-primary text-[10px] absolute -right-3 "
            f"font-bold -top-1 bg-red-700'>{badge_quantity}</div>"
        )
    )


def remove_from_cart(request, cart_item_id):
    """
    Remove an item from the cart.

    Args:
        request (HttpRequest): The HTTP request object.
        cart_item_id (int): The ID of the cart item to be removed.

    Returns:
        HttpResponse: The HTTP response containing the updated cart information.
    """
    cart_item = CartItem.objects.get(id=cart_item_id)
    cart = cart_item.cart
    cart_item.delete()
    cart_total_quantity = cart.get_total_items()
    badge_quantity = cart_total_quantity
    if badge_quantity > 99:
        badge_quantity = "99+"

    return HttpResponse(
        (
            f'<span hx-swap-oob="true" id="subtotal">'
            f"Subtotal: €{cart.get_total_price()}</span>"
            "<div id='cart-counter-badge' "
            "hx-swap-oob='true' "
            "class='w-5 h-5 text-center text-white "
            "flex items-center justify-center rounded-full "
            "bg-primary text-[10px] absolute -right-3 "
            f"font-bold -top-1 bg-red-700'>{badge_quantity}</div>"
        )
    )


def update_cart_quantity(request, cart_item_id, quantity):
    """
    Update the quantity of a cart item and return the updated cart information.

    Args:
        request (HttpRequest): The HTTP request object.
        cart_item_id (int): The ID of the cart item to update.
        quantity (int): The new quantity value.

    Returns:
        HttpResponse: The HTTP response containing the updated cart information.
    """
    cart_item = CartItem.objects.get(id=cart_item_id)
    cart = cart_item.cart
    cart_item.quantity = quantity
    cart_item.save()
    cart.save()
    cart_total_quantity = cart.get_total_items()
    badge_quantity = cart_total_quantity
    if badge_quantity > 99:
        badge_quantity = "99+"

    return HttpResponse(
        (
            f'<span hx-swap-oob="true" id="subtotal">'
            f"Subtotal: €{cart.get_total_price()}</span>"
            "<div id='cart-counter-badge' "
            "hx-swap-oob='true' "
            "class='w-5 h-5 text-center text-white "
            "flex items-center justify-center rounded-full "
            "bg-primary text-[10px] absolute -right-3 "
            f"font-bold -top-1 bg-red-700'>{badge_quantity}</div>)"
        )
    )


def cart_view(request):
    """
    View function for displaying the cart.

    If the user is authenticated, the function retrieves the cart associated with the user.
    Otherwise, it retrieves the cart associated with the session.

    Returns:
        A rendered HTML template displaying the cart items and cart details.
    """
    if request.user.is_authenticated:
        cart = Cart.objects.get_or_create(user=request.user)[0]
    else:
        cart = Cart.objects.get_or_create(session=request.session.session_key)[0]
    cart_items = cart.cartitem_set.all()

    context = {
        "cart_items": cart_items,
        "cart": cart,
    }
    return render(request, "cart/cart.html", context)

templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block content %}
    <h1 class="mb-2 text-3xl font-bold text-primary">SHOPPING BAG</h1>
    <div class="grid grid-cols-12 grid-flow-dense gap-x-4">
        {% if cart_items %}
        {% for item in cart_items %}
            <div id="item{{ item.id }}"
                 class="flex gap-6 sm:h-64 h-40 sm:col-span-9 col-span-full py-4
                        {% if forloop.first %}border-t-2{% endif %}
                        border-b-2 border-gray-300">
                <a href="{% url 'product_detail' item.item.product.id %}">
                    <div class="h-full aspect-square bg-cover bg-center bg-[url('{{ item.item.product.productimage_set.first.image.url }}')]">
                    </div>
                </a>
                <div class="flex flex-col w-full h-full">
                    <h3 class="mb-2 font-bold text-md sm:text-xl text-primary">{{ item.item.product.name }}</h3>
                    <h5 class="mb-2 font-bold">{{ item.item.get_size_display }}</h5>
                    <h4 class="mb-2 text-sm sm:text-lg text-secondary">€{{ item.item.product.get_price }} each</h4>
                    <div class="flex items-center gap-6 mt-auto">
                        <div hx-trigger="false"
                             class="flex justify-between h-8 bg-white border-2 w-28 border-primary text-primary"
                             x-data="{qty:{{ item.quantity }}}"
                             x-init="$watch('qty', value =>htmx.ajax('POST', ('update_cart_quantity/{{ item.id }}/'+qty+'/'), {target:'#subtotal', headers:{'X-CSRFToken': '{{ csrf_token }}'}}))">
                            <button class="flex items-center justify-center h-full text-white transition-all bg-black aspect-square hover:bg-secondary"
                                    x-on:click="qty > 1 ? qty-- : ''">
                                <svg width="21"
                                     height="2"
                                     viewBox="0 0 21 2"
                                     fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <line x1="0.0712891" y1="1" x2="20.1733" y2="1" stroke="white" stroke-width="2" />
                                </svg>
                            </button>
                            <!-- QTY INPUT -->
                            <input type="text"
                                   name="quantity"
                                   id="quantity"
                                   class="w-full py-3 text-lg text-center text-primary"
                                   x-text="qty"
                                   x-bind:value="qty">
                            <button hx-disable
                                    class="flex items-center justify-center h-full text-white transition-all bg-black aspect-square hover:bg-secondary"
                                    x-on:click="qty < 10 ? qty++ : ''">
                                <svg width="21"
                                     height="20"
                                     viewBox="0 0 21 20"
                                     fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M11.8827 9V0H9.88265V9H0.82666V11H9.88265V20H11.8827V11H20.9287V9H11.8827Z" fill="white" />
                                </svg>
                            </button>
                        </div>
                        <span class="underline cursor-pointer hover:font-bold text-md text-primary"
                              hx-post="{% url 'delete_cart_item' item.id %}"
                              hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                              hx-target="#item{{ item.id }}"
                              hx-swap="outerHTML">Delete</span>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="sticky flex flex-col justify-between h-48 p-6 border-2 sm:col-span-3 col-span-full border-secondary top-8">
            <h2 class="text-xl font-bold text-primary">
                <span id="subtotal">Subtotal: €{{ cart.get_total_price }}</span>
            </h2>
            <a href="{% url 'checkout' %}"
               class="w-full py-4 mt-auto font-bold text-center text-white bg-primary">CHECKOUT</a>
        </div>
        {% else %}
            <h2 class="text-xl font-bold col-span-full text-primary">Your cart is empty</h2>
        {% endif %}
    </div>
{% endblock content %}